version: '3.8'
services:
  web:
    build: .
    container_name: web
    ports:
      - "8000:8000"
    environment:
      - API_KEY=123
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: .
    container_name: worker
    command: celery -A tasks.celery_app worker --loglevel=info
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
